language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: rVMj3P1Te8cdJF3VhZbvjmINBc1USmHnt9JixXdC3Nc2p9mCk4fDZHE7+/8MtUWQRioYXvEgCQQNjIlH3bhbehFqljKdLQZqpSM/jCrSAcqhPUsYpnOHl2WpZ6hCvCBGzVMK0sjALL81lNbNcYuuhl0qquXwoCEmIgE434GcfDfohXJATGhlyj53edeckkQ6S/gp6m9I8gQs3CdKX0EWXWYk4aMQw+NNg6yjrIG1hUi1WxA4xGKd9f/APK7FrrCsyy0wj2tL4ymJmJU/oOtf/apG2cGv6Keyx3h+zp6qp3n0/jNLQV/bWca8mPDU1Oyl5EQu93HVxGmzn6qMAa6AXozv9PT4ZrTEGEaDPRsqmji9Imani6iQvTByIA9vbVnxvwrbri3lhjD8B/8prkYTEfUjcmhyyiJwWFPMWcsehYJNi7IN54Ws63D5oHFvdOY1zEehY6WNpEow0H/RY8niwoHDeuM+nynA3CwTlVXmUQBzD/EPinLQIInxrXydfXOTZhKeHllalW3irb2AJn/SNiVcFCcs7gf/CyXkowf185pxM1wQnR/hq4IzNRsRJnBwYSPSmP4Ku2DIFvbDT1ZFgSOGb8THVnMohVnGgBw344AGwiw8zTbzpJDwhImU6KRBZpqqkpmP1WJp0DixbUhW9LcpgzfuhKj9v+O/O2er9/Q=
  app: salty-crag-16434
  repo: aaronrobertson222/Grocery-list-app
